### ISSUE TITLE
Add reference to installing Plex certificate in the README

### ISSUE THREAD

**Issue by SunMar** [michealespinola/syno.plexupdate#1]
Hi,

Amazing script, thank you! :) Just installed the master version (2.9.9.1) and it worked great on my DS920+.

Perhaps a useful addition to the README file is to mention that if you used Package Center to install the version from the official Synology repository, you will need to allow packages from other publishers and add Plex to the trusted certificates as per [How to add Plex’s package signing public key to Synology NAS Package Center](https://support.plex.tv/articles/205165858-how-to-add-plex-s-package-signing-public-key-to-synology-nas-package-center/). Otherwise the update script will fail (or you have to enable allowing installation from any publisher, which for security reasons isn't ideal).

**Comment by michealespinola** [comment]
I'm glad you are enjoying it and that it worked well!

Thank you for reminding of this!  I completely agree that a requirements message should be added to the README about Plex's certificate. I had forgotten to add that because I was anticipating that the script being able to self-add the cert - but that's something I still haven't figured out how to do, so I should definately get around to adding the message to the README 😅

**Comment by michealespinola** [comment]
I hope the updated README reads well.  Thanks again for the reminder to add the certificate key info!

**Comment by SunMar** [comment]
Thanks! The `README` read great, clear steps on how to setup :).
