### ISSUE TITLE
version identification problem

### ISSUE THREAD

**Issue by justme-1968** [michealespinola/syno.plexupdate#10]
i just saw this and i think there might be a problem with the version identification. 

    Running Ver: 1.22.2.4264-6000
     Online Ver: 1.22.2.4264-b275c4330 (Beta Channel)

and later:
  
    Update from: 1.22.2.4264-6000
             to: 1.22.2.4264-b275c4330 failed!

i think the script is trying to install the same version again.

**Comment by michealespinola** [comment]
If this is what I think it is, and from what I have been told by Plex support, it's because of a recent internal numbering change made from Plex at the request of Synology in preparation for DSM7. So far this seems to particularly affect the Beta releases as also referenced in this previously reported issue:

> https://github.com/michealespinola/syno.plexupdate/issues/8#issuecomment-802740585


I believe this will sort itself out after enough time has passed to push these new version numbers through.

**Comment by justme-1968** [comment]
i see. but i'm not sure it will sort itself out as the reason is not a new versioning scheme but a difference in the version as seen in the file name and the version reported by the installed package from the same file. also as you can see in my example and the example from the linked thread the part after the - is identical in the reported version but different in the file name.

maybe the part after the dash should be ignored completely?

**Comment by michealespinola** [comment]
You're right. Thank you for engaging me about this to make me think it through. I'll have to crop the version numbers before comparing them.

**Comment by michealespinola** [comment]
This has been fixed in v3.0.2

**Comment by justme-1968** [comment]
thanks !

**Comment by michealespinola** [comment]
No problem. Thank _you_ for bringing it up and making me think about it. I didn't think it through when it was previously brought to my attention.
