### ISSUE TITLE
some random self update ideas

### ISSUE THREAD

**Issue by justme-1968** [michealespinola/syno.plexupdate#11]
here are some random ideas for the self update that just came to me when trying to get the 3.0.2 fix for the version umbers:

- have a second MinimumAge setting for the script update
- download new script versions and put them to the archive folder even if SelfUptate is set to 0
  - this would trigger the message and the user could manually check if he wants to update
  - have a --update option for the script to force the update even if SelfUpate is 0 
- keep the executable flag for the script when overwriting with the new version
- if SelfUpdate is set to 1 then first update the script and restart so the new script is used to fetch plex updates
- have a -force option to force the plex update even if MinimumAge is not met

**Comment by michealespinola** [comment]
My thoughts:

1. **Separate minimum age for script updates** / I've been thinking of this, but I'm unsure of the value. Either you want to protect yourself with a minimum age or not. If you don't trust Plex devs, you probably should trust me even less. 😅 Again, I am considering it, but I have been unable to quantify the value of it.
2. **Download everything no matter what to a locale archive** / The purpose of the script isn't to create an offline version archive of everything or alert the user to new versions. The purpose is to upgrade if stability can be safely assumed. If a version is released only a few days before a subsequent update is released - what is the value of downloading that version? If a [Public channel] version is stable and worth saving (for rollback purposes), it will remain without additional updates for at least a week.  Betas are a different story and perhaps should use a shorter minimum age if that's the update channel you want to use.
   * As a point of reference, I recently bamboozled myself by updating to Public channel PMS 1.22.1.4228 without waiting the 7 days I normally wait.  It turns out that PMS .4228 would crash immediately when any of my up-to-date android clients connected to it (it broke mobile and Nvidia Shield connections). _It was a nightmare_. Android client updates would fix the Nvidia Shield, but mobile clients still would crash the PMS. 4228 is the current release Public version, but Plex support recommends you avoid it.
4. **Update the script and restart it before checking Plex updates** / It seems logical. I'm not sure how to do it though.
5. **Force immediate update with a command-line switch** / I've been thinking about doing this.

**Comment by lordvandal** [comment]
One suggestion regarding the third point:
>     3. **Update the script and restart it before checking Plex updates** / It seems logical. I'm not sure how to do it though.

The command you probably want to use is:
**exec "$0" "$@"**

The [**exec** bash builtin command](http://www.gnu.org/software/bash/manual/bashref.html#index-exec) replaces the current program with a new one.

**$0** and **$@** are **bash [special parameters](http://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#Special-Parameters)**:

**($0)** Expands to the name of the shell or shell script. This is set at shell initialization. If Bash is invoked with a file of commands (see Shell Scripts), $0 is set to the name of that file. If Bash is started with the -c option (see Invoking Bash), then $0 is set to the first argument after the string to be executed, if one is present. Otherwise, it is set to the filename used to invoke Bash, as given by argument zero.

**($@)** Expands to the positional parameters, starting from one. In contexts where word splitting is performed, this expands each positional parameter to a separate word; if not within double quotes, these words are subject to word splitting. In contexts where word splitting is not performed, this expands to a single word with each positional parameter separated by a space. When the expansion occurs within double quotes, and word splitting is performed, each parameter expands to a separate word. That is, "$@" is equivalent to "$1" "$2" …. If the double-quoted expansion occurs within a word, the expansion of the first parameter is joined with the beginning part of the original word, and the expansion of the last parameter is joined with the last part of the original word. When there are no positional parameters, "$@" and $@ expand to nothing (i.e., they are removed).

**Comment by michealespinola** [comment]
Thank you for this, it's much appreciated! My only outlying concern is how notifications will be affected by the cycled output. This will be interesting to test

**Comment by lordvandal** [comment]
For the upgrade process I would create a temporary .lock file somewhere with some variables in it:
- script_restarted=0/1 or yes/no

And anything else you think is useful, e.g.:
- old_script_version
- new_script_version

You could even use this lock file for the Plex upgrade too.
And also to test if the script and/or Plex server upgrades were successful.

The report should be issued only after the upgrade process and the aforementioned tests.
And this way the report can contain the information about the success or failure of the upgrade too.

**Comment by michealespinola** [comment]
The report is simply a log of standard stream output from the task. Its not anything I can separately generate and email because of the limitations of the DSM. It's all very hackish, but there isn't a built-in alternative that I am aware of.

**Comment by michealespinola** [comment]
Thinking about this more while walking away from my keyboard, I think I can understand how what you suggest might be possible with various stream redirections to suppress/capture output until complete and ready to be displayed as a "report" when the script reaches its terminus.

**Comment by lordvandal** [comment]
Some quite extensive examples of self updating scripts, from [https://glennr.nl/](https://glennr.nl/):
- [https://get.glennr.nl/unifi/update/unifi-update.sh](https://get.glennr.nl/unifi/update/unifi-update.sh)
- [https://get.glennr.nl/unifi/install/install_latest/unifi-latest.sh](https://get.glennr.nl/unifi/install/install_latest/unifi-latest.sh)

**Comment by michealespinola** [comment]
I will take a look at those for ideas, thanks!
