### ISSUE TITLE
DSM 7.1 without option to add plex key certificate

### ISSUE THREAD

**Issue by ferboiar** [michealespinola/syno.plexupdate#31]
the installation instructions say to set up the plex private key in the package center and enable installation from trusted publishers. But these options do not exist in the DSM 7.1 package centre settings.

How should you configure it then?

**Comment by michealespinola** [comment]
This step is no longer need with DSM7.

The installation docs were originally written for DSM6,  where this was an important necessary step. As you have noticed, the ability to do this has been removed from DSM7.

I left the step in the instructions because I am still working on back-porting the script to be compatible with DSM6, but thanks to your observation I now see that I neglected to make a notation about it in the docs (updated).
