### ISSUE TITLE
Versioning Check is based on tagged releases

### ISSUE THREAD

**Issue by bauzer714** [michealespinola/syno.plexupdate#47]
@michealespinola - noticed that the Version Check you have implemented utilizes the "Releases" page, but missed publishing a new "Release" last year resulting in this bug after I pulled latest.

![image](https://github.com/user-attachments/assets/501492cb-6ccd-422a-985c-2a49347226b5)

**Comment by michealespinola** [comment]
The version check is intentionally based on tagged releases, not the codebase. It was made this way for the automatic script self-update feature. I had been waiting on what I though was going to be a significant change in something relating to Plex, so I had been holding off on the 4.4.1 point release in anticipation for a feature change. The change I was anticipating never materialized and 4.4.1 slipped my mind.

Due to an unexpected Plex back-end change, a bug (#46) was identified this past Friday, and a new release version will be coming out shortly (likely end of day today) that will incorporate additional uncommitted point release changes.

**Comment by bauzer714** [comment]
I assumed it was a mistake. As you prepare to commit a fix for #46  - I wanted to nudge the reminder to push the version up.

Feel free to close this unless you want to keep it open as a reminder.

**Comment by michealespinola** [comment]
No worries, and its absolutely appreciated.

**Comment by michealespinola** [comment]
Version 4.5.0 has been released
