### ISSUE TITLE
3.1.0 Update?

### ISSUE THREAD

**Issue by CrypticOne** [michealespinola/syno.plexupdate#51]
I believe some changes broke the script recently. I am still stuck on DSM 6 so I am using the 3.1 version.

Is it possible to update the old version or is it at EOL?

Thanks!

**Comment by michealespinola** [comment]
Check for more details in closed issue #48. The fix you need has been added to the archived copy of 3.1.0, here:

https://github.com/michealespinola/syno.plexupdate/blob/master/Tools/syno.plexupdate-3.1.0-DSM6.sh

I am currently rewriting a portion of the DSM7 script that handles platform checking so that this kind of descriptive name change (as detailed in that other issue) doesn't effect the script in the future. I'm hoping to re-integrate DSM6 checking into the main script at the same time, but I will need testers as I do not have a unit running DSM 6.

**Comment by CrypticOne** [comment]
Awesome! I assumed, wrongly, that it wasn't updated as the version number was still the same.

**Comment by michealespinola** [comment]
Yeah, that's my bad. I should create a new file for the versioning.

**Comment by michealespinola** [comment]
I didn't anticipate the need to upkeep this version of the script originally, so I've recreated the file as `syno.plexupdate-DSM6.sh`. 

https://github.com/michealespinola/syno.plexupdate/blob/master/Tools/syno.plexupdate-DSM6.sh
