### ISSUE TITLE
send notification only if there was any update

### ISSUE THREAD

**Issue by justme-1968** [michealespinola/syno.plexupdate#9]
just found your script and i love it. two suggestion though:

- only send notifications if there were any changes. 
- use the plex push notification system if possible

thanks
  andre

**Comment by michealespinola** [comment]
Notifications are only triggered on an actual update installation attempt (success or fail).

I'm not certain what you mean by the "plex push notification"

**Comment by justme-1968** [comment]
ok.. i think the task should be configured to send e-mails only if there was an 'error' and the script will trigger an 'error' if it wants to send the message.

this should probably mentioned in the installation instructions.


since a few weeks plex has the ability to send push notifications to mobile clients. see here: https://support.plex.tv/articles/push-notifications/

it would be great if you could figure out how to trigger such a notification from your script instead or in addition to the e-mail from the synology automation system.

**Comment by michealespinola** [comment]
There arent any tools I am aware of that I could utilize via bash/DSM to trigger a built-in Plex notification.

I'm otherwise unsure of what kind of message you want triggered.  Are you saying that you only want errors, and not be notified of successful version updates?

**Comment by justme-1968** [comment]
regarding 1.: no. its fine now. the only thing i wanted was to get no notification if nothing has changed and there was no error.
you are already taking care of this but maybe you should clarify it in the install instructions.

regarding 2.: maybe that could be asked in the plex forum

**Comment by michealespinola** [comment]
It only notifies if the condition to update is met (newer version and age requirement) and an update attempt succeeded or failed. Otherwise, there are no notifications no matter how often it is run. Even if a new update is available - an install is not attempted and you will not receive any notifications if it doesn't meet the age requirement and an install is actually attempted.

I'll add a more clear description of notifications to the docs.

Feel free to shag that question to them. If it can be done completely native to the Synology DSM with bash, I'll add it.

**Comment by justme-1968** [comment]
just did so here: https://forums.plex.tv/t/trigger-push-notifications-api/705881
